### ISSUE TITLE
Using Material theme in VoK

### ISSUE THREAD

**Issue by NiranjanShah** [mvysny/vaadin-on-kotlin#13]
What needs to be done to use 
https://github.com/appreciated/material/wiki/Installation

in VoK

**Comment by mvysny** [comment]
That theme can only be used with Vaadin 8, so for example with the vok-example-crud-sql2o example.

It is not compatible with Vaadin 10 and thus cannot be used with Beverage Buddy for example. The reason is that valo is Vaadin 8 scss-based theme, while Vaadin 10 uses lumo which is based on css variables.

**Comment by mvysny** [comment]
Closing as answered, please feel free to reopen.
