### ISSUE TITLE
How to create new Project using VoK framework

### ISSUE THREAD

**Issue by NiranjanShah** [mvysny/vaadin-on-kotlin#14]
Documentation/steps to import the VoK framework in Intenllij for new Project.

Documentation must show the steps to be used to create a new project from the scratch and importing all the files required to start a new project right from the scratch

**Comment by mvysny** [comment]
Since a typical VoK project has lots of files (migrations, views, bootstrap etc), it makes sense to have an archetype app - one that you can download or git-clone and start from that. Such an app is present here: https://github.com/mvysny/vok-helloword-app

I will add this information to the http://vaadinonkotlin.com home page. I will also create a full description of all files in the app, so that the user will know what to keep, what to modify and what to remove.

**Comment by NiranjanShah** [comment]
Hello,

I am getting error for  the below line



dependencyManagement {
    imports { mavenBom "com.vaadin:vaadin-bom:$vaadin10_version" }
}

Error is : Configuration with name 'vaadin10_version' not found.


For your reference attaching the build.gradle file been used to start a new project.

PS: We are creating a new project and want to use flow. Kindly guide, in case, we are missing anything.







Regards
Niranjan G Shah

**Comment by mvysny** [comment]
If you're starting with Flow, then please try out https://github.com/mvysny/beverage-buddy-vok/ - I will document that as well.

**Comment by NiranjanShah** [comment]
Yes Martin,

We have used the build.gradle as specified in the beverage-buddy-vok.

however , in the WelcomeView.kt, we get the below error.


Error:(12, 2) Kotlin: Unresolved reference: AutoView
Error:(16, 9) Kotlin: Unresolved reference: isMargin
Error:(17, 9) Kotlin: Unresolved reference: verticalLayout
Error:(18, 13) Kotlin: Unresolved reference: alignment
Error:(19, 13) Kotlin: Unresolved reference: isMargin
Error:(20, 13) Kotlin: Unresolved reference: label
Error:(23, 13) Kotlin: Unresolved reference: image
Error:(24, 13) Kotlin: Unresolved reference: label
Error:(24, 21) Kotlin: Unresolved reference: html
Error:(25, 13) Kotlin: Unresolved reference: label
Error:(25, 21) Kotlin: Unresolved reference: html
Error:(26, 13) Kotlin: Unresolved reference: label
Error:(26, 21) Kotlin: Unresolved reference: html

Regards
Niranjan G Shah

**Comment by mvysny** [comment]
Uh-oh. WelcomeView.kt uses Vaadin 8, which is totally incompatible with Vaadin 10. Vaadin 10 is a complete rewrite of the Vaadin framework; only a few concepts of Vaadin 8 are applicable to Vaadin 10 apps. You can't paste Vaadin 8 code into Vaadin 10 - such compatibility layer is not available as of now.

You will need to decide whether you want to use Vaadin 8 or Vaadin 10; according to that decision you should either start with https://github.com/mvysny/vok-helloword-app (Vaadin 8) or the Beverage Buddy (Vaadin 10).

**Comment by NiranjanShah** [comment]
Thank you, Thank you for the clarification.

And it is such drastic change!!!!, so how are existing Vaadin developers moving to Flow?


Regards
Niranjan G Shah

**Comment by mvysny** [comment]
The migration path from Vaadin 8 to Vaadin 10 is still unclear. We will have to wait until Vaadin 10 is actually released (it's still in alpha state and not yet released); then I'm sure that a documentation related to migration will be eventually published.

Since the VoK documentation has been updated, I'll close this bug report. Please feel free to ask further questions at https://vaadin.com/forum/#!/category/1007558
