### ISSUE TITLE
Grid + editor.setEnabled(true) == Editing items inside a Grid.

### ISSUE THREAD

**Issue by skoude** [mvysny/vaadin-on-kotlin#5]
In vaadin 7 it was much easier to make grid columns editable. We just called .setEditorEnabled(true) and just did override preComit() and PostCommit methods for Cancel and Save functionality.  In Vaadin 8(I'm just migrating it from Vaadin 7) we have to use  [Binder](https://vaadin.com/docs/-/part/framework/components/components-grid.html) Could it be possible to develop an auto binding for Grid components editor.setEnabled(true) method?  I mean for example if I have a grid like:

```
personGrid = grid(Person::class, "List of Persons", dataProvider = personsListProvider) {
            expandRatio = 1f;
            setSizeFull()
            appendHeaderRow().generateFilterComponents(this, Person::class)
        }

```

and then inside that personGrid I would just call: `editor.setEnabled(true)`  so then it would just automatically create editing components for selected Person object?   Then if we wan't / need easily override `setEnabled(true)` by  using our custom bindings (for example if we don't want to edit every field, or some field need Calendar etc).....   Any idea what I'm talking about?  Or is there a really easy way to do this in vaadin-on-kotlin and Vaadin 8, that I'm not aware about?

**Comment by skoude** [comment]
This was just way too simple:)


just do:
```
 column(Person::firstName) {
                setEditorComponent(TextField("firstname"), Person::firstName.setter)
                isEditable = true
                isHidden = false

            }
```

then  for listeners..

```
 editor.addCancelListener( { event -> Notification.show("Editing Cancelled...") } )
 editor.addSaveListener({ event -> Notification.show("Saved ${event.bean.firstName}...") })
```

and then finally:
` editor.setEnabled(true)`


closing this :)

**Comment by mvysny** [comment]
Awesome find, thank you! Thanks for documenting your findings, it will definitely be helpful for future users as well.

Since Vaadin-on-Kotlin is but a thin wrap over the Vaadin API, I'd suggest to seek help at Vaadin forums - there are more guys there and I believe you can get help sooner.

I remember there was possibility to even generate those editor fields (similarly how we generate filter fields). In Vaadin 7 there was `EditorFieldFactory` but it is deprecated without any replacement. I wonder why...
