### ISSUE TITLE
Relation to Vaadin

### ISSUE THREAD

**Issue by chkpnt** [mvysny/vaadin-on-kotlin#59]
Hi @mvysny,

I'm wondering why this project doesn't reside at https://github.com/vaadin/, as this project is referenced in the [official documentation](https://vaadin.com/docs/v14/flow/getting-started/getting-started-kotlin.html)

> Vaadin supports the Kotlin programming language through the Karibu-DSL library, [...]

(I'm unsure if Vaadin means "Vaadin, the framework" or "Vaadin, the company" in this sentence.)

I can see in your GitHub profile you somehow belong to Vaadin Ltd., so I guess this started as a side project at some time. But what is the current state of relation between this project and Vaadin?

**Comment by mvysny** [comment]
Hi, thank you for reaching out! Good question which definitely needs some clarification.

Both VoK and Karibu-DSL are not officially supported by Vaadin Ltd (=Vaadin the company), and also there is no plan in adding of official support in the near future. Official support in this case means that the core Vaadin Ltd team is actively maintaining the project - which is not the case in VoK and Karibu-DSL.

However, VoK and Karibu-DSL are not "just" community projects. The reason is that I, as a Vaadin Ltd employee, am able to use a slice of my working time to maintain VoK and Karibu-DSL. Also, Vaadin Ltd is happy to consult a VoK and Karibu-DSL project.

That places VoK and Karibu-DSL somewhere in the middle, into the "half-supported" territory :+1: 

The advantage on top of that is that they're both fully open-source, so you can actually check the activity of those projects. The projects are also so very simple that anyone is able to maintain them, even in the company in-house in the worst case.

> Vaadin supports the Kotlin programming language

This means that Vaadin the Framework "supports" Kotlin since both are JVM-based and thus compatible; on top of that there's Karibu-DSL which takes advantage of Kotlin-specific language features.

Please let me know if this makes things clearer :)

**Comment by chkpnt** [comment]
Thank you very much for the detailed explanation. The things are now indeed clearer for me :-)
