### ISSUE TITLE
Question issue: Kotlin DSL

### ISSUE THREAD

**Issue by hfazai** [mvysny/vaadin-on-kotlin#69]
I see that there is two ways to design a kotlin DSL : 

1st way: 

````KOTLIN
class Body { }

fun Body.button (init: Button.() -> Unit) { }

class Button {
  var text: String? = null
}
````

2nd way: The advantage here is that you dont need to import `button`.

````KOTLIN
class Body {
  fun button (init: Button.() -> Unit) { }
}

class Button {
  var text: String? = null
}
````

My question is why functional programming is prefered in Kotlin DSL while you can use the second way to get rid of the imports?

**Comment by mvysny** [comment]
The only difference between those examples is that the second way uses class member functions, while the first way uses extension functions.

All DSL extension functions extend the `HasComponents` class instead of `Body`. Since Karibu-DSL doesn't own the `HasComponents` class (it's hosted in Vaadin Core), we can't add member functions into `HasComponents` which makes the second way impossible to do. Hence I'm using the first way.

**Comment by hfazai** [comment]
Hi @mvysny 

Sorry if the example was confusing but it is not related VOK. I'm talking in general if someone is independant of an other framework and want to design a DSL. For Example in Exposed, all DSL elements are an extension functions (for example `Table.select()`) so you need to import select for every usage.

**Comment by mvysny** [comment]
Hmm. I've read somewhere that the member functions contain the most core functionality of the class while the extension functions are more like utility functions, containing functionality That's not that important. So maybe this is what you are observing. But I am not familiar with the exposed framework, so maybe they're using another semantics

**Comment by hfazai** [comment]
The idea looks very reasonable. Thanks for the explanation, it was very helpful :+1: 

I will also ask the same question in Exposed's repo and share with if I get any other information.
