### ISSUE TITLE
Feature requests for Beverage Buddy example app

### ISSUE THREAD

**Issue by WakeRealityDev** [mvysny/vaadin-on-kotlin#9]
I think it's a useful enough starting app that it's worth making a ToDo list of features... for anyone who wants to take them on.  This isn't intended as a complaint.

1.  I can not find a way to list all reviews by Category in the UI
2. The categories page should be refactored to use the same right-column "Edit" that the Reviews uses.
3.  On Category page, default clicking of a category name should list all the reviews in that category.
3a. On Reviews page, clicking of category should list reviews in that category.
4. Reviews (and Categories?) list should have paging options when many rows available
5. Does the framework have any language localization for strings? Such as the headings of "Search" "Reviews", button "New Review"?  It would be nice to have a way to test/change languages to say Spanish for just these hand-full of words to demonstrate the coding technique best practices.
6. Reviews page have a sort pick:  Drink name, times tasted, date
7. More complex: I notice this app is entirely JavaScript on the client side, the body  tag is empty except for a noscript message.  It would be perhaps useful to show a fallback mode of this simple app as a best-practice? Just to show coding best practices for a noscript app?

Thank you.

**Comment by mvysny** [comment]
Thanks! Please note that this app is a clone of https://github.com/vaadin/beverage-starter-flow . Therefore, it's best to report enhancements to the app there; once accepted and implemented, I'll port them here.

1. 2. 3. Yup, the functionality is missing, I guess it's for the sake of simplicity. The app is not meant to be feature-complete; instead it tries to demonstrate the core concepts of Vaadin 10. For a more complete app please try out the Bakery App: https://vaadin.com/flow/demo Unfortunately the Bakery App is not freely available and I can't port it to Kotlin just now, so it's Java only as of now.
4. The Reviews list demoes the Polymer template along with `dom-repeat`, hence it would not make sense to complicate the example further with paging. However, the Categories uses the Grid component which supports paging natively.
5. No localization support as of now; but you're right that it would be great to have at least some basic support using Java ResourceBundles.
7. Unfortunately that's not possible since Vaadin 10 requires JavaScript enabled and can not work without JS. But maybe I'm wrong - please try to ask the Vaadin guys directly at https://github.com/vaadin/beverage-starter-flow/issues

**Comment by mvysny** [comment]
The Beverage Buddy has been moved to https://github.com/mvysny/beverage-buddy-vok . Closing, please open a new feature request at https://github.com/mvysny/beverage-buddy-vok if necessary.
